// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as SettingService from "./settingservice.js";
import * as TaskService from "./taskservice.js";
import * as WindowService from "./windowservice.js";
export {
    SettingService,
    TaskService,
    WindowService
};
