// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function HideMainAndShowFloating(): $CancellablePromise<void> {
    return $Call.ByID(4249623474);
}

export function ShowMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(2318204229);
}
