// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function FloatingStickySide(): $CancellablePromise<number> {
    return $Call.ByID(3966789445);
}

export function HideMainAndShowFloating(): $CancellablePromise<void> {
    return $Call.ByID(4149804132);
}

export function HideSettings(): $CancellablePromise<void> {
    return $Call.ByID(1241998358);
}

export function IsInitializeSuccess(): $CancellablePromise<boolean> {
    return $Call.ByID(1440561984);
}

export function ShowMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(1290021111);
}

export function ShowSettings(): $CancellablePromise<void> {
    return $Call.ByID(1393607803);
}
