// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Setting {
    "id": number;
    "created_at"?: number;
    "updated_at"?: number;
    "key"?: string;
    "value"?: string | null;
    "group_name"?: string;
    "name"?: string;
    "desc"?: string;
    "order_num"?: number;

    /**
     * 是否在设置界面展示
     */
    "showable"?: boolean | null;

    /**
     * 设置项类型，值为input/select/checkbox/switch等
     */
    "setting_type"?: string;

    /**
     * 可选值，仅在Type为select/checkbox时有效，格式为JSON数组
     */
    "options"?: string;

    /**
     * 占用列数，默认1，最大12
     */
    "cols"?: number;

    /** Creates a new Setting instance. */
    constructor($$source: Partial<Setting> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     */
    static createFrom($$source: any = {}): Setting {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Setting($$parsedSource as Partial<Setting>);
    }
}
